#federation服务器
FEDERATION_SERVER = "http://www.lxq.com:8002/federation"

#compliance服务器
AUTH_SERVER = "http://www.lxq.com:8003"

#签名账户
SIGNING_KEY = "GD4BPFPKOBVRNR7KE4RMFHJBQD3JNU5REZU2RRZ7ESBA6BTV643EXESA"

#货币，可以有多个
[[CURRENCIES]]
code="bdc"
issuer="GDM264FZR2B5YO7X4ERHFSAZYM2YRO5IC5UZFL7G27YFKB3XEULYKI35"
